name: Pike Module (pmod)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MODULE/**'
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pike-version: ["7.8-latest", "8.0-latest"]

    container:
      image: pikelang/pike:${{ matrix.pike-version }}
      volumes:
        - ${{ github.workspace }}:/github/workspace

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check module compilation on ${{ matrix.pike-version }}
        run: |
          pike -M /github/workspace/MODULE -e "indices(Public.Standards.CSV)"