name: Pike Module (pmod)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MODULE/**'
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pike-version: ["7.8-latest", "8.0-latest"]

    container:
      image: pikelang/pike:${{ matrix.pike-version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check module compilation on ${{ matrix.pike-version }}
        run: |
          id
          ls -al /
          ls -alR /github/workspace
          ls -alR /home/runner/work/
          ls -al ${{ github.workspace }}
          cd ${{ github.workspace }}
          pike -M MODULE -e "indices(Public.Standards.CSV)"