name: Pike Module (pmod)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths: ["MODULE/**", "testsuite"]

jobs:

  Testsuite-OCI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pike-version: ["7.8-latest", "8.0-latest", "8.0-latest-slim"]

    container:
      image: pikelang/pike:${{ matrix.pike-version }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      env:
        PIKE_MODULE_PATH: ${{ github.workspace }}/MODULE

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests against ${{ matrix.pike-version }}
        run: |
          cd ${{ github.workspace }}
          pike -x test_pike testsuite

  Testsuite-Ubuntu:
    runs-on: ubuntu-latest
    env:
      PIKE_MODULE_PATH: ${{ github.workspace }}/MODULE
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Pike
        uses: ConorMacBride/install-package@v1
        with:
          apt: pike8.0 pike8.0-core pike8.0-image pike8.0-gdbm pike8.0-pcre pike8.0-mysql pike8.0-pg pike8.0-dev
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          pike -x test_pike testsuite

  Testsuite-macOS:
    run-on: macos-latest
    env:
      PIKE_MODULE_PATH: ${{ github.workspace }}/MODULE
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Pike
        uses: ConorMacBride/install-package@v1
          with:
            brew: pike
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          pike -x test_pike testsuite