name: Pike Module (pmod)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ["MODULE/**", "testsuite"]

jobs:

  Testsuite-OCI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pike-version: ["7.8-latest", "8.0-latest", "8.0-latest-slim"]

    container:
      image: pikelang/pike:${{ matrix.pike-version }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      env:
        PIKE_MODULE_PATH: ${{ github.workspace }}/MODULE

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests against ${{ matrix.pike-version }}
        run: |
          cd ${{ github.workspace }}
          pike -x test_pike testsuite